version: "3"

services:
  xtend:
    build: .
    image: xtend
    container_name: xtend
    volumes:
      - .:/xtend_volume
    working_dir: /xtend_volume
    command: python3 /xtend_volume/src/main.py
    profiles:
      - run
      - all

  xtend-test:
    build: .
    image: xtend
    container_name: xtend-test
    volumes:
      - .:/xtend_volume
    working_dir: /xtend_volume
    command: python -m unittest discover tests
    profiles:
      - test
      - all

